package com.axa.dm.travel;

import java.lang.Number;

rule "Initialization"
	dialect "mvel"
	lock-on-active true
	when
		ProcessObject( $travel : travel != null )
	then
	    insert($travel);
end

rule "Check discount process"
    dialect "mvel"
    when
        $travel : Travel(discount == null, processedDiscount == false)
    then
        $travel.setProcessedDiscount(true);
        update($travel);
end